[project]
authors = ["Edward Chee <edward_chee@foundrysoft.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ragtrain"
platforms = ["osx-arm64"]
version = "0.1.0"


[dependencies]
python = ">3.13"
pytest = "*"
scipy = "*" # ">=1.15.1,<2"
aiofiles = "*" # ">=24.1.0,<25"
pytest-asyncio = "*" # ">=0.25.3,<0.26"
tiktoken = "*" # ">=0.9.0,<0.10"
numpy = ">=2.2.3,<3"
pytorch = "2.6.0"
transformers = ">=4.48.3,<5"
pydantic-settings = ">=2.7.1,<3"
## Bypass conda's dependency resolver
## Gets packages directly from pip
pip = { version = ">=25.0.1,<26", channel = "conda-forge" }
sentence-transformers = "*"


[tasks]
post-install = "pip install chromadb==0.6.3"
